# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: BanditHijo.dev
email: bandithijo@duck.com
description: Here's where I started writing some notes that someday I will call it, a book
baseurl: "" # the subpath of your site, e.g. /blog
url: https://bandithijo.dev # the base hostname & protocol for your site, e.g. http://example.com
author: Rizqi Nur Assyaufi
keywords: bandithijo, rizqi nur assyaufi, arch linux, vim, neovim, i3wm, dwm, suckless, jekyll, thinkpad, ruby, rails, ruby on rails


# Missing timezone in metadata date can lead to wrong date in url
timezone: Asia/Makassar


# Google Analytics
google_analytics: UA-116004889-1
google_tag: G-688BWZGJ84


# Google Site Verification (Webmaster)
google_verify: qXp9Kgb5hIHVp5T9vFOa_motqUmNuF5STbkJKF70wLc


# Opengraph
lang: id
logo_author: /assets/images/logo_author.png
image: /assets/images/banner/about_bandithijo.png


# Navigations
nav_top:
  - title: Blog
    url: /blog/
  - title: Note
    url: /note/
  - title: Portfolio
    url: /portfolio/
  - title: About
    url: /about/
nav_bottom:
  - title: Books
    url: /books/
  - title: Dotfriends
    url: /dotfriends/
  - title: Contact
    url: /contact/
  - title: Stats
    url: /stats/


# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
tailwindcss:
  config: "./tailwind.config.js"
  css_path: ./_tailwind.css


# Sitemap Generator
sitemap:
  filename: "/sitemap.xml"
  exclude:
    - "/feed.xml"
  include_posts:
    - "/index.html"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Procfile.dev
