build:
  command: bundle exec jekyll build --config _config.yml, _config_netlify.yml
  commandOrigin: ui
  environment:
    - JEKYLL_ENV
    - RUBY_VERSION
  publish: /opt/build/repo/_site
  publishOrigin: ui
redirects:
  - force: true
    from: https://bandithijo.netlify.app/*
    status: 301
    to: https://bandithijo.dev/:splat
redirectsOrigin: config
